title: Tattoo_tak
description: 'باسلام '
template:
  repo: tattoo_tak-template
  name: tattoo_tak
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
